default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/rtts/djhtml
    rev: 3.0.6
    hooks:
      - id: djhtml
        files: .*/templates/.*\.html$
      - id: djcss
        files: .*/static/css/.*\.css$
      - id: djjs
        files: .*/static/js/.*\.js$

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [ "--profile", "black", "--filter-files" ]