services:
  neo4j:
    image: neo4j:5.20.0
    ports:
      - "7888:7474"
      - "7999:7687"
    environment:
      - NEO4J_AUTH=$DB_USERNAME/$DB_PASSWORD
    volumes:
      - ./.db/data:/data
      - ./.db/conf:/conf
      - ./.db/logs:/logs
      - ./.db/plugins:/plugins

    healthcheck:
      test: wget http://0.0.0.0:7474 || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s

  backend:
    build:
      context: .
      dockerfile: docker/backend-dev.dockerfile
    ports:
      - "8080:8000"
    environment:
      - DB_SCHEME=neo4j
      - DB_HOST=neo4j
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_PORT=7687
      - DB_NAME=neo4j
    depends_on:
      neo4j:
        condition: service_healthy
    volumes:
      - .:/src

  nginx:
    build:
      context: .
      dockerfile: docker/nginx-dev.dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
