services:
  neo4j:
    image: neo4j:5.20.0
    ports:
      - "7888:7474"
      - "7999:7687"
    environment:
      - NEO4J_AUTH=$DB_USERNAME/$DB_PASSWORD
    volumes:
      - ./.db/data:/data
      - ./.db/conf:/conf
      - ./.db/logs:/logs
      - ./.db/plugins:/plugins

    healthcheck:
      test: wget http://0.0.0.0:7474 || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s

  postgres-database:
    image: postgres:16.3
    restart: always
    ports:
      - "$POSTGRES_PORT:5432"
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - ./.postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 2s
      timeout: 10s
      retries: 5
      start_period: 5s

  backend:
    build:
      context: .
      dockerfile: docker/backend-dev.dockerfile
    ports:
      - "8080:8000"
    environment:
      - DB_SCHEME=neo4j
      - DB_HOST=neo4j
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_PORT=7687
      - DB_NAME=neo4j
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_PORT=$POSTGRES_PORT
      - SECRET_KEY=$SECRET_KEY
      - ADMIN_PASSWORD=$ADMIN_PASSWORD
      - AUTH_SECRET_KEY=$AUTH_SECRET_KEY
    depends_on:
      neo4j:
        condition: service_healthy
      postgres-database:
        condition: service_healthy

    volumes:
      - .:/src

  nginx:
    build:
      context: .
      dockerfile: docker/nginx-dev.dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
