services:
  neo4j:
    image: neo4j:5.20.0
    ports:
      - "7888:7474"
      - "7999:7687"
    environment:
      - NEO4J_AUTH=$DB_USERNAME/$DB_PASSWORD
    volumes:
      - ./.db/data:/data
      - ./.db/conf:/conf
      - ./.db/logs:/logs
      - ./.db/plugins:/plugins

    healthcheck:
      test: wget http://0.0.0.0:7474 || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s

  backend:
    build:
      context: .
      dockerfile: docker/backend.dockerfile
    ports:
      - "8080:8000"
    environment:
      - DB_SCHEME=neo4j
      - DB_HOST=neo4j
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_PORT=7687
      - DB_NAME=neo4j
    depends_on:
      neo4j:
        condition: service_healthy

  nginx:
    build:
      context: .
      dockerfile: docker/nginx.dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.nginx/conf.d:/etc/nginx/conf.d
      - ./.nginx/ssl:/etc/nginx/ssl
      - ./.nginx/log:/var/log/nginx
    depends_on:
      - backend
      - certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./.nginx/ssl:/etc/letsencrypt
      - ./.nginx/ssl-dhparams:/ssl-dhparams
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  cron:
    image: alpine:latest
    container_name: cron
    volumes:
      - ./.nginx/ssl:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'echo \"0 0 * * * certbot renew --webroot -w /var/www/certbot/ && nginx -s reload\" | crontab - && crond -f'"

  webroot:
    image: nginx:latest
    container_name: webroot
    volumes:
      - ./.nginx/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'mkdir -p /var/www/certbot && nginx -g \"daemon off;\"'"
    networks:
      - default